import { Platform, StyleSheet } from "react-native";
import { Colors } from "../../../constants/theme";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#e5e5ea" },
  list: { padding: 16, paddingBottom: 140 },
  bubble: {
    maxWidth: "80%",
    padding: 12,
    borderRadius: 22,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    flexDirection: "row",
    alignItems: "center",
    position: "relative",
  },
  bubbleContent: {
    flexShrink: 1,
  },
  bubbleHighlighted: {
    borderWidth: 1,
    borderColor: "#0A84FF",
    shadowOpacity: 0.2,
    shadowRadius: 8,
  },
  bubbleMe: {
    alignSelf: "flex-end",
    backgroundColor: Colors.light.bubbleMe,
    borderBottomRightRadius: 6,
  },
  bubbleMeGradient: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 22,
    borderBottomRightRadius: 6,
  },
  bubbleOther: {
    alignSelf: "flex-start",
    backgroundColor: Colors.light.bubbleOther,
    borderBottomLeftRadius: 6,
  },
  bubbleText: {
    fontSize: 16,
    fontFamily: Platform.select({
      ios: "San Francisco",
      android: "Roboto",
      default: "Arial",
    }),
  },
  bubbleTextMe: {
    color: Colors.light.bubbleTextMe,
  },
  bubbleTextOther: {
    color: Colors.light.bubbleTextOther,
  },
  edited: {
    fontSize: 12,
    color: "#888",
    marginLeft: 6,
    alignSelf: "flex-end",
  },
  messageImageWrapWithText: {
    marginTop: 8,
  },
  messageImage: {
    width: 220,
    borderRadius: 14,
    backgroundColor: "rgba(0, 0, 0, 0.06)",
  },
  replyQuote: {
    borderRadius: 10,
    borderLeftWidth: 3,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 8,
  },
  replyQuoteMe: {
    backgroundColor: "rgba(107, 68, 37, 0.14)",
    borderLeftColor: "#A56D3D",
  },
  replyQuoteOther: {
    backgroundColor: "rgba(0, 0, 0, 0.04)",
    borderLeftColor: "#4B5563",
  },
  replyQuoteLabel: {
    fontSize: 12,
    fontWeight: "600",
    marginBottom: 2,
  },
  replyQuoteLabelMe: {
    color: "#5F371A",
  },
  replyQuoteLabelOther: {
    color: "#374151",
  },
  replyQuoteText: {
    fontSize: 13,
  },
  replyQuoteTextMe: {
    color: "#4A2E18",
  },
  replyQuoteTextOther: {
    color: "#111827",
  },
  typingBubbleContainer: {
    alignSelf: "flex-start",
    marginTop: 2,
    marginBottom: 8,
  },
  typingBubble: {
    minWidth: 58,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  composerContainer: {
    borderTopWidth: 1,
    borderColor: "#e5e5ea",
    backgroundColor: "#f9f9f9",
  },
  replyComposer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 4,
  },
  replyComposerTextWrap: {
    flex: 1,
  },
  replyComposerLabel: {
    color: "#0A84FF",
    fontSize: 12,
    fontWeight: "600",
  },
  replyComposerText: {
    color: "#4B5563",
    fontSize: 13,
    marginTop: 1,
  },
  replyComposerClose: {
    marginLeft: 8,
    height: 24,
    width: 24,
    borderRadius: 12,
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
  },
  replyComposerCloseText: {
    color: "#4B5563",
    fontSize: 14,
    fontWeight: "700",
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#f9f9f9",
  },
  attachBtn: {
    height: 34,
    width: 34,
    borderRadius: 17,
    backgroundColor: "#E5E7EB",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  attachBtnText: {
    color: "#374151",
    fontWeight: "700",
    fontSize: 20,
    lineHeight: 20,
    marginTop: -2,
  },
  input: {
    flex: 1,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    fontSize: 16,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#e5e5ea",
  },
  pendingImageComposer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingTop: 8,
    paddingBottom: 4,
  },
  pendingImageThumb: {
    width: 44,
    height: 44,
    borderRadius: 10,
  },
  pendingImageMetaWrap: {
    flex: 1,
    marginLeft: 10,
  },
  pendingImageMetaText: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "500",
  },
  pendingImageRemoveBtn: {
    marginLeft: 10,
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E5E7EB",
  },
  pendingImageRemoveText: {
    color: "#4B5563",
    fontSize: 14,
    fontWeight: "700",
  },
  editContainer: {
    width: "100%",
  },
  editInput: {
    width: "100%",
    minHeight: 44,
    maxHeight: 180,
    borderRadius: 14,
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    lineHeight: 22,
    borderWidth: 1,
    borderColor: "#d1d5db",
    color: Colors.light.bubbleTextOther,
  },
  editActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    marginTop: 8,
  },
  editCancelBtn: {
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginRight: 8,
    backgroundColor: "rgba(0, 0, 0, 0.07)",
  },
  editCancelText: {
    color: "#374151",
    fontWeight: "600",
    fontSize: 13,
  },
  sendBtn: {
    backgroundColor: "#007AFF",
    borderRadius: 20,
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  sendBtnDisabled: {
    opacity: 0.5,
  },
  saveBtn: {
    backgroundColor: "#0A84FF",
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  saveBtnText: {
    color: "#fff",
    fontWeight: "600",
    fontSize: 13,
  },
  imageViewerBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.86)",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 20,
    paddingVertical: 40,
  },
  imageViewerImage: {
    width: "100%",
    height: "100%",
  },
  messageActionSheetOverlay: {
    flex: 1,
    justifyContent: "flex-end",
  },
  messageActionSheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(0, 0, 0, 0.28)",
  },
  messageActionSheetCard: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 24,
  },
  messageActionSheetEmojiScroll: {
    marginBottom: 6,
  },
  messageActionSheetEmojiRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    paddingRight: 6,
  },
  messageActionSheetEmojiButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F3F4F6",
    marginRight: 10,
  },
  messageActionSheetEmojiText: {
    fontSize: 24,
  },
  messageActionSheetRow: {
    paddingVertical: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#E5E7EB",
    alignItems: "center",
  },
  messageActionSheetRowText: {
    fontSize: 16,
    color: "#111827",
    fontWeight: "500",
  },
  messageActionSheetCancelText: {
    fontSize: 16,
    color: "#DC2626",
    fontWeight: "600",
  },
});
