import { StyleSheet } from "react-native";

import { Colors } from "../../../constants/theme";
import { unity } from "../../utils/general";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.light.background },
  map: { flex: 1 },

  // -------- Overlays --------
  topOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    paddingHorizontal: unity * 12,
    paddingTop: unity * 8,
    gap: unity * 8,
  },

  // The notice the tracker cannot dismiss: they are seen looking.
  noticeChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: Colors.light.tint,
    borderRadius: unity * 18,
    paddingVertical: unity * 8,
    paddingHorizontal: unity * 12,
    gap: unity * 8,
    shadowColor: "#000",
    shadowOpacity: 0.18,
    shadowRadius: unity * 6,
    shadowOffset: { width: 0, height: unity * 2 },
    elevation: 3,
  },
  noticeChipText: {
    color: "#fff",
    fontSize: unity * 13,
    fontWeight: "600",
    flexShrink: 1,
  },

  // -------- Watched chips --------
  watchedRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: unity * 8,
  },
  watchedChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    borderRadius: unity * 16,
    paddingVertical: unity * 6,
    paddingHorizontal: unity * 10,
    gap: unity * 6,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: unity * 4,
    shadowOffset: { width: 0, height: unity * 1 },
    elevation: 2,
  },
  watchedChipText: {
    fontSize: unity * 13,
    fontWeight: "600",
    color: Colors.light.text,
  },
  watchedChipAge: { fontSize: unity * 11, color: Colors.light.icon },

  // -------- The ceiling on a look --------
  dropdownRowDisabled: { opacity: 0.45 },

  expiryChip: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#FFF1DB",
    borderRadius: unity * 16,
    paddingVertical: unity * 7,
    paddingHorizontal: unity * 11,
    gap: unity * 7,
    borderWidth: unity * 1,
    borderColor: "#E8C48B",
  },
  expiryChipText: {
    fontSize: unity * 13,
    fontWeight: "600",
    color: "#8A4B00",
  },
  endedCard: {
    alignSelf: "stretch",
    backgroundColor: "#fff",
    borderRadius: unity * 14,
    paddingVertical: unity * 12,
    paddingHorizontal: unity * 14,
    gap: unity * 10,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    shadowColor: "#000",
    shadowOpacity: 0.12,
    shadowRadius: unity * 8,
    shadowOffset: { width: 0, height: unity * 2 },
    elevation: 3,
  },
  endedHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: unity * 7,
  },
  endedTitle: {
    fontSize: unity * 13,
    fontWeight: "700",
    color: Colors.light.text,
    letterSpacing: unity * 0.3,
  },
  endedRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: unity * 10,
  },
  endedName: {
    flexShrink: 1,
    fontSize: unity * 15,
    fontWeight: "600",
    color: Colors.light.text,
  },
  resumeButton: {
    backgroundColor: Colors.light.tint,
    borderRadius: unity * 14,
    paddingVertical: unity * 7,
    paddingHorizontal: unity * 13,
  },
  resumeButtonText: {
    color: "#fff",
    fontSize: unity * 13,
    fontWeight: "700",
  },
  endedFootnote: {
    fontSize: unity * 11,
    lineHeight: unity * 15,
    color: Colors.light.icon,
  },

  // -------- Other trackees dropdown --------
  dropdownAnchor: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#fff",
    borderRadius: unity * 16,
    paddingVertical: unity * 8,
    paddingHorizontal: unity * 12,
    gap: unity * 6,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    elevation: 2,
  },
  dropdownAnchorText: {
    fontSize: unity * 13,
    fontWeight: "600",
    color: Colors.light.text,
  },
  dropdownSheet: {
    backgroundColor: "#fff",
    borderRadius: unity * 14,
    paddingVertical: unity * 6,
    marginTop: unity * 4,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    shadowColor: "#000",
    shadowOpacity: 0.14,
    shadowRadius: unity * 10,
    shadowOffset: { width: 0, height: unity * 4 },
    elevation: 6,
    overflow: "hidden",
  },
  dropdownHint: {
    fontSize: unity * 11,
    color: Colors.light.icon,
    paddingHorizontal: unity * 14,
    paddingBottom: unity * 6,
    paddingTop: unity * 2,
  },
  dropdownRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: unity * 11,
    paddingHorizontal: unity * 14,
    gap: unity * 10,
  },
  dropdownRowText: { fontSize: unity * 15, color: Colors.light.text, flex: 1 },
  dropdownRowMeta: { fontSize: unity * 12, color: Colors.light.icon },
  dropdownDivider: {
    height: unity * 1,
    backgroundColor: Colors.light.border,
    marginHorizontal: unity * 14,
  },

  // -------- Auto-fit chip --------
  autoFitChip: {
    position: "absolute",
    right: unity * 12,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(20,20,22,0.86)",
    borderRadius: unity * 18,
    paddingVertical: unity * 8,
    paddingHorizontal: unity * 12,
    gap: unity * 8,
  },
  autoFitChipText: { color: "#fff", fontSize: unity * 13, fontWeight: "600" },
  autoFitCountdown: {
    minWidth: unity * 20,
    textAlign: "center",
    color: Colors.light.bubbleMe,
    fontSize: unity * 13,
    fontWeight: "700",
    fontVariant: ["tabular-nums"],
  },

  // -------- Marker --------
  marker: { alignItems: "center" },
  markerLabel: {
    backgroundColor: "#fff",
    borderRadius: unity * 10,
    paddingHorizontal: unity * 8,
    paddingVertical: unity * 4,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    maxWidth: unity * 160,
  },
  markerLabelText: {
    fontSize: unity * 12,
    fontWeight: "700",
    color: Colors.light.text,
  },
  markerLabelAge: { fontSize: unity * 10, color: Colors.light.icon },
  markerBody: {
    marginTop: unity * 4,
    width: unity * 38,
    height: unity * 38,
    borderRadius: unity * 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: unity * 2,
    borderColor: "#fff",
    shadowColor: "#000",
    shadowOpacity: 0.25,
    shadowRadius: unity * 4,
    shadowOffset: { width: 0, height: unity * 2 },
  },
  markerBodyLive: { backgroundColor: Colors.light.tint },
  markerBodyStale: { backgroundColor: "#9AA0A6" },
  markerPointer: {
    width: 0,
    height: 0,
    borderLeftWidth: unity * 6,
    borderRightWidth: unity * 6,
    borderTopWidth: unity * 8,
    borderLeftColor: "transparent",
    borderRightColor: "transparent",
    marginTop: -unity * 1,
  },
  markerPointerLive: { borderTopColor: Colors.light.tint },
  markerPointerStale: { borderTopColor: "#9AA0A6" },

  // -------- Empty / permission states --------
  centered: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: unity * 28,
    gap: unity * 10,
  },
  emptyTitle: {
    fontSize: unity * 19,
    fontWeight: "700",
    color: Colors.light.text,
    textAlign: "center",
  },
  emptyBody: {
    fontSize: unity * 14,
    color: Colors.light.icon,
    textAlign: "center",
    lineHeight: unity * 20,
  },
  primaryButton: {
    backgroundColor: Colors.light.tint,
    borderRadius: unity * 12,
    paddingVertical: unity * 12,
    paddingHorizontal: unity * 20,
    marginTop: unity * 6,
  },
  primaryButtonText: { color: "#fff", fontWeight: "700", fontSize: unity * 15 },
});
