import { StyleSheet } from "react-native";

import { Colors } from "../../../constants/theme";
import { unity } from "../../utils/general";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: Colors.light.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: unity * 16,
    paddingTop: unity * 8,
    paddingBottom: unity * 8,
    borderBottomWidth: unity * 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.background,
  },
  headerTitle: {
    fontSize: unity * 22,
    fontWeight: "bold",
    color: Colors.light.text,
  },
  headerAction: {
    flexDirection: "row",
    alignItems: "center",
    gap: unity * 6,
    paddingVertical: unity * 6,
    paddingHorizontal: unity * 10,
    borderRadius: unity * 14,
    backgroundColor: Colors.light.tint,
  },
  headerActionText: { color: "#fff", fontWeight: "700", fontSize: unity * 13 },

  scroll: { paddingBottom: unity * 32 },
  sectionTitle: {
    fontSize: unity * 13,
    fontWeight: "700",
    color: Colors.light.icon,
    textTransform: "uppercase",
    letterSpacing: unity * 0.6,
    marginTop: unity * 22,
    marginBottom: unity * 8,
    marginHorizontal: unity * 16,
  },
  sectionNote: {
    fontSize: unity * 12,
    color: Colors.light.icon,
    marginHorizontal: unity * 16,
    marginBottom: unity * 8,
    lineHeight: unity * 17,
  },

  card: {
    backgroundColor: Colors.light.bubbleOther,
    borderTopWidth: unity * 1,
    borderBottomWidth: unity * 1,
    borderColor: Colors.light.border,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: unity * 12,
    paddingHorizontal: unity * 16,
    gap: unity * 12,
  },
  rowDivider: {
    height: unity * 1,
    backgroundColor: Colors.light.border,
    marginLeft: unity * 74,
  },
  avatar: {
    width: unity * 46,
    height: unity * 46,
    borderRadius: unity * 23,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: Colors.light.tint,
  },
  avatarText: { color: "#fff", fontWeight: "600", fontSize: unity * 18 },
  rowInfo: { flex: 1, gap: unity * 2 },
  rowName: {
    fontSize: unity * 17,
    fontWeight: "600",
    color: Colors.light.text,
  },
  rowStatus: { fontSize: unity * 13, color: Colors.light.icon },
  rowStatusWarn: { fontSize: unity * 13, color: "#B4541F" },

  rowButtons: { flexDirection: "row", gap: unity * 8 },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: unity * 5,
    paddingVertical: unity * 8,
    paddingHorizontal: unity * 12,
    borderRadius: unity * 16,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.background,
  },
  actionButtonPrimary: {
    backgroundColor: Colors.light.tint,
    borderColor: Colors.light.tint,
  },
  actionButtonText: {
    fontSize: unity * 13,
    fontWeight: "700",
    color: Colors.light.text,
  },
  actionButtonDisabled: {
    backgroundColor: Colors.light.inputBar,
    borderColor: Colors.light.border,
    opacity: 0.75,
  },
  actionButtonTextDisabled: { color: Colors.light.icon },
  actionButtonTextPrimary: { color: "#fff" },
  actionButtonTextDanger: { color: "#B00020" },

  // Sits inside the button rather than pinned to its corner: the count is part
  // of what the button says ("Chat, 3 waiting"), not a decoration floating over
  // it, and an inline badge can't clip against the row's edge.
  actionBadge: {
    minWidth: unity * 20,
    height: unity * 20,
    borderRadius: unity * 10,
    paddingHorizontal: unity * 6,
    backgroundColor: "#E5342B",
    alignItems: "center",
    justifyContent: "center",
  },
  actionBadgeText: {
    color: "#fff",
    fontSize: unity * 12,
    fontWeight: "800",
    // Digits in a pill look low without this on iOS.
    includeFontPadding: false,
    textAlign: "center",
  },

  requestActions: { flexDirection: "row", gap: unity * 8 },

  // -------- Guardianship --------
  menuSheet: {
    marginTop: "auto",
    backgroundColor: Colors.light.background,
    borderTopLeftRadius: unity * 18,
    borderTopRightRadius: unity * 18,
    paddingBottom: unity * 34,
    paddingHorizontal: unity * 8,
  },
  menuItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: unity * 14,
    paddingVertical: unity * 16,
    paddingHorizontal: unity * 12,
  },
  menuItemText: { flex: 1, gap: unity * 3 },
  menuItemTitle: {
    fontSize: unity * 16,
    fontWeight: "700",
    color: Colors.light.text,
  },
  menuItemBody: {
    fontSize: unity * 13,
    lineHeight: unity * 18,
    color: Colors.light.icon,
  },
  menuDivider: {
    height: unity * 1,
    backgroundColor: Colors.light.border,
    marginHorizontal: unity * 12,
  },

  codeBox: {
    backgroundColor: Colors.light.inputBar,
    borderRadius: unity * 14,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    paddingVertical: unity * 22,
    alignItems: "center",
    marginTop: unity * 18,
  },
  codeText: {
    fontSize: unity * 34,
    fontWeight: "800",
    letterSpacing: unity * 4,
    color: Colors.light.text,
    fontVariant: ["tabular-nums"],
  },
  codeExpiry: {
    marginTop: unity * 8,
    textAlign: "center",
    fontSize: unity * 13,
    color: Colors.light.icon,
    fontVariant: ["tabular-nums"],
  },
  codeSteps: { marginTop: unity * 20, gap: unity * 8 },
  codeStep: {
    fontSize: unity * 14,
    lineHeight: unity * 19,
    color: Colors.light.text,
  },
  codeFootnote: {
    marginTop: unity * 18,
    fontSize: unity * 12,
    lineHeight: unity * 17,
    color: Colors.light.icon,
  },
  codeErrorBox: { marginTop: unity * 20, gap: unity * 8 },
  codeErrorText: {
    marginTop: unity * 10,
    fontSize: unity * 14,
    color: "#B00020",
  },
  codeRetry: {
    fontSize: unity * 14,
    fontWeight: "700",
    color: Colors.light.tint,
  },
  codeInput: {
    marginTop: unity * 18,
    backgroundColor: Colors.light.inputBar,
    borderRadius: unity * 12,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    paddingVertical: unity * 16,
    fontSize: unity * 26,
    fontWeight: "700",
    letterSpacing: unity * 3,
    textAlign: "center",
    color: Colors.light.text,
  },

  consentBox: {
    marginTop: unity * 16,
    backgroundColor: "#FFF1DB",
    borderRadius: unity * 12,
    borderWidth: unity * 1,
    borderColor: "#E8C48B",
    padding: unity * 14,
    gap: unity * 9,
  },
  consentLine: {
    fontSize: unity * 13,
    lineHeight: unity * 18,
    color: "#5A3B0A",
  },
  consentButton: {
    marginTop: unity * 18,
    backgroundColor: Colors.light.tint,
    borderRadius: unity * 14,
    paddingVertical: unity * 15,
    alignItems: "center",
  },
  consentButtonDisabled: { opacity: 0.4 },
  consentButtonText: {
    color: "#fff",
    fontSize: unity * 16,
    fontWeight: "700",
  },

  guardianStatus: {
    fontSize: unity * 13,
    fontWeight: "600",
    color: "#8A4B00",
  },
  guardianNotice: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: unity * 8,
    backgroundColor: "#FFF1DB",
    paddingVertical: unity * 10,
    paddingHorizontal: unity * 14,
    marginHorizontal: unity * 12,
    marginBottom: unity * 12,
    borderRadius: unity * 10,
  },
  guardianNoticeText: {
    flex: 1,
    fontSize: unity * 12,
    lineHeight: unity * 17,
    color: "#5A3B0A",
  },
  releaseButton: {
    borderRadius: unity * 16,
    borderWidth: unity * 1,
    borderColor: Colors.light.border,
    paddingVertical: unity * 8,
    paddingHorizontal: unity * 12,
    backgroundColor: Colors.light.background,
  },
  releaseButtonText: {
    fontSize: unity * 13,
    fontWeight: "700",
    color: "#B00020",
  },
  releasePending: {
    marginHorizontal: unity * 12,
    marginBottom: unity * 12,
    padding: unity * 12,
    borderRadius: unity * 10,
    backgroundColor: Colors.light.inputBar,
  },
  releasePendingText: {
    fontSize: unity * 12,
    lineHeight: unity * 17,
    color: Colors.light.text,
  },
  requestBody: {
    fontSize: unity * 13,
    color: Colors.light.icon,
    lineHeight: unity * 18,
    paddingHorizontal: unity * 16,
    paddingBottom: unity * 12,
  },

  historyRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: unity * 10,
    paddingVertical: unity * 10,
    paddingHorizontal: unity * 16,
  },
  historyText: { flex: 1, fontSize: unity * 14, color: Colors.light.text },
  historyMeta: { fontSize: unity * 12, color: Colors.light.icon },

  empty: {
    paddingHorizontal: unity * 16,
    paddingVertical: unity * 18,
    gap: unity * 6,
  },
  emptyTitle: {
    fontSize: unity * 15,
    fontWeight: "600",
    color: Colors.light.text,
  },
  emptyBody: {
    fontSize: unity * 13,
    color: Colors.light.icon,
    lineHeight: unity * 19,
  },

  // -------- Contact picker --------
  modalBackdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "flex-end",
  },
  modalSheet: {
    backgroundColor: "#fff",
    borderTopLeftRadius: unity * 18,
    borderTopRightRadius: unity * 18,
    paddingBottom: unity * 28,
    maxHeight: "72%",
  },
  modalHandle: {
    alignSelf: "center",
    width: unity * 40,
    height: unity * 4,
    borderRadius: unity * 2,
    backgroundColor: Colors.light.border,
    marginVertical: unity * 10,
  },
  modalTitle: {
    fontSize: unity * 18,
    fontWeight: "700",
    color: Colors.light.text,
    marginHorizontal: unity * 16,
  },
  modalBody: {
    fontSize: unity * 13,
    color: Colors.light.icon,
    marginHorizontal: unity * 16,
    marginTop: unity * 4,
    marginBottom: unity * 10,
    lineHeight: unity * 19,
  },
});
